#!/usr/bin/env bash
# Linux / WSL build: clang + Ninja (C++ modules need a module-aware generator).
#
#   scripts/build_linux.sh [debug|release] [--test] [--run] [--smoke]
#
# Toolchain lookup (first match wins):
#   CC/CXX env vars, then ~/toolchains/LLVM-*/bin, then clang/clang++ on PATH.
#   cmake: ~/toolchains/cmake-*/bin, then PATH.
# The CMake files are generated by pyke on Windows and committed, so pyke is optional here: when
# PYKE=<path to a Linux pyke binary> is set and the .pyke file is newer, it is regenerated first.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="Debug"
RUN_TESTS=0
RUN_APP=0
SMOKE=0
for l_arg in "$@"; do
    case "$l_arg" in
        debug) CONFIG="Debug" ;;
        release) CONFIG="Release" ;;
        --test) RUN_TESTS=1 ;;
        --run) RUN_APP=1 ;;
        --smoke) SMOKE=1 ;;
        *) echo "unknown argument: $l_arg" >&2; exit 1 ;;
    esac
done
BUILD_DIR="$ROOT/build-linux-${CONFIG,,}"

newest() { ls -d $1 2>/dev/null | sort -V | tail -1; }

if [[ -z "${CXX:-}" ]]; then
    LLVM_DIR="$(newest "$HOME/toolchains/LLVM-*")"
    if [[ -n "$LLVM_DIR" ]]; then
        export CC="$LLVM_DIR/bin/clang" CXX="$LLVM_DIR/bin/clang++"
    else
        export CC=clang CXX=clang++
    fi
fi

CMAKE_DIR="$(newest "$HOME/toolchains/cmake-*")"
CMAKE="${CMAKE_DIR:+$CMAKE_DIR/bin/}cmake"
CTEST="${CMAKE_DIR:+$CMAKE_DIR/bin/}ctest"

PYKE_BIN="${PYKE:-}"
if [[ -n "$PYKE_BIN" && "$ROOT/whiteboard.pyke" -nt "$ROOT/CMakeLists.txt" ]]; then
    (cd "$ROOT" && "$PYKE_BIN" whiteboard.pyke .)
fi

echo "== $CONFIG build with $("$CXX" --version | head -1) / $("$CMAKE" --version | head -1)"
if [[ ! -f "$BUILD_DIR/CMakeCache.txt" ]]; then
    "$CMAKE" -S "$ROOT" -B "$BUILD_DIR" -G Ninja -DCMAKE_BUILD_TYPE="$CONFIG" \
        -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX"
fi
"$CMAKE" --build "$BUILD_DIR" --parallel

if [[ $RUN_TESTS -eq 1 ]]; then
    "$CTEST" --test-dir "$BUILD_DIR" --output-on-failure
fi
if [[ $SMOKE -eq 1 ]]; then
    "$BUILD_DIR/app/inkwell" --smoke-test=120
fi
if [[ $RUN_APP -eq 1 ]]; then
    "$BUILD_DIR/app/inkwell"
fi
